apiVersion: apps/v1
kind: Deployment
metadata:
  name: privesc-deployment
  namespace: privesc-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: privesc-pod
  template:
    metadata:
      labels:
        app: privesc-pod
    spec:
      serviceAccountName: privesc-sa
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command: ["sleep", "infinity"] 
